#!/usr/bin/env bash
# Provision a fresh Sanction wallet + agent for the eve tester demo, set a
# demo-friendly policy, vault two demo credentials, and write .env.
#
#   bash scripts/provision-demo.sh            # uses live API
#   SANCTION_API_URL=http://localhost:3000/api/v1 bash scripts/provision-demo.sh
set -euo pipefail

HERE="$(cd "$(dirname "$0")/.." && pwd)"
API="${SANCTION_API_URL:-https://getsanction.com/api/v1}"
EMAIL="${1:-eve-demo+$RANDOM@sanction.dev}"
py(){ python3 -c "import sys,json;d=json.load(sys.stdin);print(d.get('$1',''))"; }

echo "▶ wallet…"
W=$(curl -s -X POST "$API/wallets" -H "content-type: application/json" \
  -d "{\"name\":\"eve-testers\",\"owner_email\":\"$EMAIL\"}")
WID=$(echo "$W" | py id); MGMT=$(echo "$W" | py management_key)
[ -n "$WID" ] && [ -n "$MGMT" ] || { echo "✗ wallet create failed: $W"; exit 1; }

echo "▶ agent…"
AK=$(curl -s -X POST "$API/agents" -H "x-mgmt-key: $MGMT" -H "content-type: application/json" \
  -d "{\"wallet_id\":\"$WID\",\"name\":\"eve-tester\"}" | py api_key)
[ -n "$AK" ] || { echo "✗ agent create failed"; exit 1; }

echo "▶ policy → auto-approve <\$20 · escalate \$20–50 · deny >\$50 · block crypto/gambling/adult · daily token \$5…"
curl -s -X PATCH "$API/wallets/policy" -H "x-mgmt-key: $MGMT" -H "content-type: application/json" \
  -d "{\"wallet_id\":\"$WID\",\"per_transaction_max_usd\":50,\"escalate_over_usd\":20,\"daily_spend_budget_usd\":500,\"daily_token_budget_usd\":5,\"blocked_categories\":[\"crypto\",\"gambling\",\"adult\"]}" >/dev/null

echo "▶ vault → STRIPE_KEY (clearance 1, operator can read) + ROOT_DB_URL (clearance 5, red-team can't)…"
curl -s -X POST "$API/credentials/vault" -H "x-mgmt-key: $MGMT" -H "content-type: application/json" \
  -d "{\"wallet_id\":\"$WID\",\"label\":\"STRIPE_KEY\",\"type\":\"api_key\",\"value\":\"sk_test_DEMO_do_not_use\",\"min_clearance\":1}" >/dev/null
curl -s -X POST "$API/credentials/vault" -H "x-mgmt-key: $MGMT" -H "content-type: application/json" \
  -d "{\"wallet_id\":\"$WID\",\"label\":\"ROOT_DB_URL\",\"type\":\"password\",\"value\":\"postgres://demo-not-real\",\"min_clearance\":5}" >/dev/null

# Preserve an existing ANTHROPIC_API_KEY if .env already has one.
PREV_ANTHROPIC=""
[ -f "$HERE/.env" ] && PREV_ANTHROPIC=$(grep -E '^ANTHROPIC_API_KEY=' "$HERE/.env" | head -1 | cut -d= -f2- || true)

cat > "$HERE/.env" <<EOF
# Generated by scripts/provision-demo.sh — DO NOT COMMIT
SANCTION_API_URL=$API
SANCTION_API_KEY=$AK
SANCTION_WALLET_ID=$WID
SANCTION_MGMT_KEY=$MGMT
SANCTION_MCP_URL=http://127.0.0.1:8808/mcp
SANCTION_MCP_PORT=8808
ANTHROPIC_API_KEY=${PREV_ANTHROPIC}
EOF

echo
echo "✓ wrote $HERE/.env"
echo "   wallet_id      = $WID"
echo "   agent api_key  = ${AK:0:10}…"
[ -z "$PREV_ANTHROPIC" ] && echo "   ⚠ set ANTHROPIC_API_KEY in .env (eve's model) before running."
echo
echo "next:  bash scripts/start-bridge.sh   (in one terminal)"
echo "       npm run dev                      (in another — eve agents)"
echo "       bash scripts/run-scenarios.sh    (drive the demo)"
echo "dashboard: ${API%/api/v1}/dashboard/spend"
